# Generated by Django 2.2.5 on 2020-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drink_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('price', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='item',
            new_name='food_item',
        ),
    ]
