# Generated by Django 2.2.5 on 2020-01-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200120_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(default=0)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
