# Generated by Django 2.2.5 on 2020-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pizza_qty', models.IntegerField(default=0)),
                ('Burger_qty', models.IntegerField(default=0)),
                ('Noodles_qty', models.IntegerField(default=0)),
                ('Coffee_qty', models.IntegerField(default=0)),
                ('Tea_qty', models.IntegerField(default=0)),
                ('Juice_qty', models.IntegerField(default=0)),
                ('total_bill', models.IntegerField(default=0)),
            ],
        ),
    ]
