# Generated by Django 2.2.5 on 2020-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Table_num',
            field=models.IntegerField(default=0),
        ),
    ]
